---
dependency:
  name: galaxy
driver:
  name: docker
docker:
  containers:
    - name: node1
      image: alpine:latest
      ansible_groups:
        - group1
    - name: node2
      image: alpine:latest
      ansible_groups:
        - group1
lint:
  name: yamllint
platforms:
  - name: node1
    image: alpine
    ansible_groups: [test_molecule]
  - name: node2
    image: alpine
    ansible_groups: [test_molecule]
provisioner:
  name: ansible
  # log: true
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
ansible:
